spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-wr1ttenyu-dev
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-wr1ttenyu-test