spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    
server:
  port: 7002

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false 表示不向注册中心注册自己。
    fetch-registry: false     #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
---
spring:
    profiles: test

server:
  port: 7003    
    
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false 表示不向注册中心注册自己。
    fetch-registry: false     #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务